application: twitter-username-availability
version: 1
runtime: python
api_version: 1

handlers:
- url: /tasks/.*
  script: twitter-username-availability.py
  login: admin
- url: /*
  script: twitter-username-availability.py
